name = "puny-url"
compatibility_date = "2024-09-14"
compatibility_flags = [ "nodejs_compat" ]

[vars]
UPSTASH_REDIS_REST_URL = "redis-url"
UPSTASH_REDIS_REST_TOKEN = "redis-token"
FRONTEND_URL = "frontend-url"